// Generated by https://quicktype.io

export interface Block {
   object: string;
   id: string;
   parent: Parent;
   created_time: string;
   last_edited_time: string;
   created_by: TedBy;
   last_edited_by: TedBy;
   has_children: boolean;
   archived: boolean;
   type: string;
   paragraph: Paragraph;
   heading_1: Paragraph;
   heading_2: Paragraph;
   heading_3: Paragraph;
   bulleted_list_item: Paragraph;
   numbered_list_item: Paragraph;
}

export interface TedBy {
   object: string;
   id: string;
}

export interface Paragraph {
   rich_text: RichText[];
   color: string;
}

export interface RichText {
   type: string;
   text: Text;
   annotations: Annotations;
   plain_text: string;
   href: null;
}

export interface Annotations {
   bold: boolean;
   italic: boolean;
   strikethrough: boolean;
   underline: boolean;
   code: boolean;
   color: string;
}

export interface Text {
   content: string;
   link: null;
}

export interface Parent {
   type: string;
   page_id: string;
}
