// Generated by https://quicktype.io

export interface Post {
   object: string;
   id: string;
   created_time: string;
   last_edited_time: string;
   created_by: TedBy;
   last_edited_by: TedBy;
   cover: null;
   icon: null;
   parent: Parent;
   archived: boolean;
   properties: Properties;
   url: string;
   public_url: null;
}

export interface TedBy {
   object: string;
   id: string;
}

export interface Parent {
   type: string;
   database_id: string;
}

export interface Properties {
   URL: URL;
   servings: Description;
   description: Description;
   time_in_minutes: Description;
   name: Name;
}

export interface URL {
   id: string;
   type: string;
   url: string;
}

export interface Description {
   id: string;
   type: string;
   rich_text: RichText[];
}

export interface RichText {
   type: string;
   text: Text;
   annotations: Annotations;
   plain_text: string;
   href: null;
}

export interface Annotations {
   bold: boolean;
   italic: boolean;
   strikethrough: boolean;
   underline: boolean;
   code: boolean;
   color: string;
}

export interface Text {
   content: string;
   link: null;
}

export interface Name {
   id: string;
   type: string;
   title: RichText[];
}
